added leaderboard
jmcmurtry/wikiclue pull request #17
Opened 2024-03-12 22:26 UTC by Kjeon7

2024-03-12 22:35 UTC, harrisonMondragon commented on wikiclue/src/styles/leaderboardStyles.css
> +.leader-container {
Does this scale well with the px sizes?

2024-03-12 22:50 UTC, jmcmurtry requested changes
I pushed a quick change to this branch to update the styling for smaller screen sizes. Everything looks good but could you add some sample data to each leaderboard so they look like the Figma? Then when we have real data we don't have to write the html and css for it.

2024-03-13 03:56 UTC, jmcmurtry requested changes

2024-03-13 03:56 UTC, jmcmurtry commented on wikiclue/src/routes/leaderboard/+page.svelte
> +                <p class="leader-name">Bonnie <span class ="leader-score">7</span></p>
Could we make the vertical spacing between each row of name and score a bit less for all three leaderboards? And could we make the font size a bit smaller? Therefore we can fit more users on each leaderboard and also accommodate longer usernames.

2024-03-13 16:55 UTC, jmcmurtry approved these changes

2024-03-13 19:00 UTC, merged