Kjeon7/feature/friend management
jmcmurtry/wikiclue pull request #25
Opened 2024-03-17 05:05 UTC by Kjeon7

![image](https://github.com/jmcmurtry/wikiclue/assets/72672852/3b13c02a-2351-47fe-8fd9-32f2856a7a76)
![image](https://github.com/jmcmurtry/wikiclue/assets/72672852/a324020a-00e7-4050-a66d-8261c8d829a6)

Mobile: 
![image](https://github.com/jmcmurtry/wikiclue/assets/72672852/d5ab785e-5681-46d6-a76d-27d8fc4c0f66)
![image](https://github.com/jmcmurtry/wikiclue/assets/72672852/a7950ba3-f569-42f5-8e7c-a62f18ed1cf5)

2024-03-18 05:49 UTC, jmcmurtry requested changes

2024-03-18 05:49 UTC, jmcmurtry commented on wikiclue/src/routes/friend-requests/+page.svelte
> +    {#if $friendAddOverlayVis}
Can we remove this overlay and just show a green message when you accept a request that says like "success! friend added" or something. Look at what is done on the add friend page if you type something in the bar and click add friend.

2024-03-18 05:49 UTC, jmcmurtry commented on wikiclue/src/routes/friend-requests/+page.svelte
> +            <div class ="users-container">
Can we put this in a scroll view in case there are more users than can fit?

2024-03-18 05:49 UTC, jmcmurtry commented on wikiclue/src/routes/manage-friends/+page.svelte
> +            <div class ="users-container">
Can we also put this in a scrollview in case there are more users than can fit in the box?

2024-03-18 05:49 UTC, jmcmurtry commented on wikiclue/src/routes/manage-friends/+page.svelte
> +            <div class="button-container">
Can we make the yes and no buttons in here bigger? They look super small. Maybe add a lot more padding. 
![Screenshot 2024-03-17 233855](https://github.com/jmcmurtry/wikiclue/assets/77893842/06fd5604-469b-408b-aa3e-794bcf544923)

2024-03-18 05:49 UTC, jmcmurtry commented on wikiclue/src/routes/manage-friends/+page.svelte
> +                <p class="friend-name">Clyde <button on:click={() => {friendRemoveOverlayVis.set(true)}}>Remove</button> </p>
Can we make the remove button bigger? Maybe a bit more padding as they look small on a larger screen
![Screenshot 2024-03-17 233832](https://github.com/jmcmurtry/wikiclue/assets/77893842/47e76940-3578-4590-8d34-47e37286268c)

2024-03-19 19:57 UTC, harrisonMondragon approved these changes
LGTM

2024-03-21 02:59 UTC, jmcmurtry approved these changes

2024-03-21 02:59 UTC, merged